export enum TbaMediaKind {
	Youtube = 'youtube',
	CdPhotoThread = 'cdphotothread',
	Imgur = 'imgur',
	FacebookProfile = 'facebook-profile',
	YoutubeChannel = 'youtube-channel',
	TwitterProfile = 'twitter-profile',
	GithubProfile = 'github-profile',
	InstagramProfile = 'instagram-profile',
	PeriscopeProfile = 'periscope-profile',
	GitlabProfile = 'gitlab-profile',
	Grabcad = 'grabcad',
	InstagramImage = 'instagram-image',
	ExternalLink = 'external-link',
	Avatar = 'avatar',
}
