name: autofix.ci # needed to securely identify the workflow

on: [push, pull_request]

permissions:
  contents: read

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1.21.1
        with:
          cache: true
      - name: Fix formatting and lint issues
        continue-on-error: true
        run: vp check --fix
      - name: Fix Knip issues
        continue-on-error: true
        run: vp exec knip --fix
      - name: Run autofix.ci
        uses: autofix-ci/action@v1
        with:
          commit-message: 'refactor: apply automatic fixes'
