name: autofix.ci # needed to securely identify the workflow

on: [push, pull_request]

permissions:
  contents: read

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v3
        with:
          cache: true
      - name: Fix formatting
        continue-on-error: true
        run: pnpm format:fix
      - name: Fix lint issues
        continue-on-error: true
        run: pnpm run lint:fix
      - name: Fix Knip issues
        continue-on-error: true
        run: pnpm knip --fix
      - name: Run autofix.ci
        uses: autofix-ci/action@v1
        with:
          commit-message: 'refactor: apply automatic fixes'
