name: CI

on: [push, pull_request]

permissions:
  contents: read

env:
  NEXT_PUBLIC_CONVEX_URL: https://example.convex.cloud

jobs:
  build-and-test:
    name: Build and test

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v3
        with:
          cache: true
      - name: Check formatting
        run: pnpm format
      - name: Lint
        run: pnpm lint
      - name: Type check
        run: pnpm type-check
      - name: Run Knip
        run: pnpm knip
      - name: Build
        run: pnpm build
